name: Build and Publish Docker image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from pyproject.toml
        id: get_version
        run: |
          VERSION=$(grep '^version =' pyproject.toml | sed -E "s/version = \"([^\"]+)\"/\1/")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set lowercase repository name
        id: repo_name
        run: |
          echo "repo_lower=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build Docker image with multiple tags
        run: |
          docker build \
            -t ghcr.io/${{ steps.repo_name.outputs.repo_lower }}:latest \
            -t ghcr.io/${{ steps.repo_name.outputs.repo_lower }}:${{ steps.get_version.outputs.version }} .

      - name: Push Docker images
        run: |
          docker push ghcr.io/${{ steps.repo_name.outputs.repo_lower }}:latest
          docker push ghcr.io/${{ steps.repo_name.outputs.repo_lower }}:${{ steps.get_version.outputs.version }}